### ISSUE TITLE
Open Source / Project Status for Microsoft.SystemForCrossDomainIdentityManagement

### ISSUE THREAD

**Issue by Cephei** [Azure/AzureAD-BYOA-Provisioning-Samples#5]
I'm unsure where best to communicate these questions as I've found little information on the package and development of Microsoft.SystemForCrossDomainIdentityManagement.

Today I just happened upon this repository and the Azure AD provisioning msdn article promoting the MS SCIM Nuget package.  Recently, I had been working to implement SCIM 2.0 as an Owin extension at https://github.com/PowerDMS/Owin.Scim

I was thrilled to find out that MS had already done this.  After a decent look at MS's implementation, however, there's a lot that's missing and I want to make sure I'm not mistaken since the source is not available.

Whenever you have some free time, can you please help with the following:

1.  
Microsoft's implementation does not provide validation of resources in any create, update, replace operations.  This is concerning SCIM's protocol rule-processing: (ie. mutability, multiValuedAttribute.Primary, canonicalization, locale, preferred language, etc etc)

2.  
Patch support is very basic.  All an IProvider.Update seems to get is a basic object representing the `attrExp / logExp / valuePath`.  This makes patching very tedious and offers no compliance to SCIM's specific error reporting concerning patch operations.  
Some of the work I've done with query filters parses a SCIM filter into an expression tree that can be used directly as a LINQ predicate or turned into sql (if they want to spend that effort writing that visitor).  
  
3. What is the status of this project?  Will it be open sourced or at least, in active development?  Is there a team committed to this with a roadmap?

I'm trying to determine whether it's worth continuing my work or can contribute feedback/ideas/code to the MS team.  
  
  
Thanks for your help!
-Daniel Gioulakis

**Comment by craigmcm** [comment]
An announcement to explain the context of this project will be made within a few days.  Follow @AzureAD on Twitter to catch it.  You can mail me directly at craigmcm@microsoft.com, or you can call me, during Pacific Standard Time daylight hours, in my office at 425.707.9810.  My colleagues and I will be standing behind this project and will enhance it as we engage with our community.  

I wrote a bunch of text in reply to your first and second points, but I've since deleted them to focus on the crux of the matter, which is captured in your statement that you are "trying to determine whether it's worth continuing my work or can [instead] contribute [requirements]" to our team."  The answer to that question depends on how our objectives align.  If the reason that you started your work corresponds with what we're hoping to enable folk to do, then I'd be delighted to deepen our implementation to cover your requirements  The announcement should clarify our objective.

**Comment by Cephei** [comment]
I really appreciate the response and look forward to the announcement.  After further exploring your SCIM implementation it looks like I could benefit greatly from the foundations your team has built.  Technically-speaking, the work I've done would not go to waste but suit well to expand upon your design of the `ProviderAdapterTemplate<T>` - but applied towards another template-based abstraction derived from `ProviderBase`.

Essentially, I'd no longer need to build out endpoints, schema, bulk support, etc ... the core elements, and focus on building developer-extensibility options around resource validation/canonicalization, enhancing query functionality, automated patching (which has been implementing borrowing concepts from MS' JsonPatch impl), and other aspects that fill any gaps to the protocol's rule processing and error reporting.

Thanks again for all yours and your colleague's hard work!  This is very exciting news for cloud service and identity providers.
